### ISSUE TITLE
rake pwb:db:seed error

### ISSUE THREAD

**Issue by amerov** [etewiah/property_web_builder#29]
```
rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Section must exist
/home/amerov/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/validations.rb:78:in `raise_validation_error'
/home/amerov/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/validations.rb:50:in `save!'
/home/amerov/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/attribute_methods/dirty.rb:43:in `save!'
/home/amerov/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/transactions.rb:313:in `block in save!'
/home/amerov/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/transactions.rb:384:in `block in with_transaction_returning_status'
/home/amerov/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:225:in `block in transaction'
/home/amerov/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
/home/amerov/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
/home/amerov/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:225:in `transaction'
/home/amerov/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/transactions.rb:210:in `transaction'
/home/amerov/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/transactions.rb:381:in `with_transaction_returning_status'
/home/amerov/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/transactions.rb:313:in `save!'
/home/amerov/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/suppressor.rb:46:in `save!'
/home/amerov/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/persistence.rb:51:in `create!'
/home/amerov/.rvm/gems/ruby-2.4.1/bundler/gems/property_web_builder-b7b7ab306b36/lib/pwb/seeder.rb:133:in `block in seed_content'
/home/amerov/.rvm/gems/ruby-2.4.1/bundler/gems/property_web_builder-b7b7ab306b36/lib/pwb/seeder.rb:121:in `each'
/home/amerov/.rvm/gems/ruby-2.4.1/bundler/gems/property_web_builder-b7b7ab306b36/lib/pwb/seeder.rb:121:in `seed_content'
/home/amerov/.rvm/gems/ruby-2.4.1/bundler/gems/property_web_builder-b7b7ab306b36/lib/pwb/seeder.rb:24:in `seed!'
/home/amerov/.rvm/gems/ruby-2.4.1/bundler/gems/property_web_builder-b7b7ab306b36/lib/tasks/pwb_tasks.rake:15:in `block (3 levels) in <top (required)>'
/home/amerov/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/amerov/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
/home/amerov/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => pwb:db:seed
(See full trace by running task with --trace)
```

**Comment by amerov** [comment]
Sorry. I did't see rails versions support.

**Comment by etewiah** [comment]
Hi there, I was just about to let you know this.  It seems to only happen with rails 5.1.0.  You are the second person this week who has tried reported this so I will try to fix it.  It is just that I have a dependency on https://github.com/etewiah/comfortable-mexican-sofa which does not yet support 5.1.0 but I will create a fork of that and see if that will work.

**Comment by etewiah** [comment]
The master branch should support Rails 5.1.0 now.

**Comment by etewiah** [comment]
Can you please confirm that this works so I can close the issue.
