### ISSUE TITLE
I have tried to follow emberjs admin functions.. but i have trouble..

### ISSUE THREAD

**Issue by calebyk** [etewiah/property_web_builder#59]
// propertyResource: {},
    actions: {
    createPropertyResource: function() {
      var propertyResource = this.get("resourceObject");
      var self = this;

      function transitionToPost(propertyResource) {
        self.get('router').transitionTo('properties.editar',  propertyResource.id);
      }

      function failure(reason) {
        // handle the error
      }
        propertyResource.save().then(transitionToPost).catch(failure);
      }
    }

when I traced it with a debugger, I found it couldn't pass through payload part and jumped to callback.. and throw that error, even couldn't request server api..

"Error: Assertion Failed: '(unknown mixin)' does not appear to be an ember-data model
    at new EmberError (http://localhost:4200/assets/vendor.js:24258:25)
    at Object.assert (http://localhost:4200/assets/vendor.js:24501:15)
    at Class._modelFactoryFor (http://localhost:4200/assets/vendor.js:113899:42)
    at Class._modelFor (http://localhost:4200/assets/vendor.js:113878:29)
    at Class.modelFor (http://localhost:4200/assets/vendor.js:113870:17)
    at Function.typeForRelationship (http://localhost:4200/assets/vendor.js:104499:34)
    at Function._findInverseFor (http://localhost:4200/assets/vendor.js:104559:28)
    at Function.inverseFor (http://localhost:4200/assets/vendor.js:104551:38)
    at Function.determineRelationshipType (http://localhost:4200/assets/vendor.js:104843:24)
    at Class._shouldSerializeHasMany (http://localhost:4200/assets/vendor.js:119601:44)"

**Comment by etewiah** [comment]
Hi @calebyk , I see you have opened the same issue in the PWB admin repo.  Let us follow it up on there.

**Comment by calebyk** [comment]
Thank you!!
