### ISSUE TITLE
Lack of development instructions/can't get test suite to pass

### ISSUE THREAD

**Issue by SteveRedka** [etewiah/property_web_builder#75]
Hi.

I wanted to do some enhancements, but I couldn't even set up pwb separately locally.

Most of the tests fail with:
```
Missing `secret_key_base` for 'test' environment, set this value in `config/secrets.yml`
```
Although the key is set in `config.yml.travis`. Putting it into said `config/secrets.yml` doesn't affect anything.

`rails server` fails with this error:
```bash
/home/how/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/command/actions.rb:8:in `set_application_directory!': uninitialized constant Rails::Command::Actions::APP_PATH (NameError)
	from /home/how/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:129:in `perform'
	from /home/how/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /home/how/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/how/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /home/how/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/command/base.rb:63:in `perform'
	from /home/how/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/command.rb:44:in `invoke'
	from /home/how/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
	from /home/how/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/engine/commands.rb:7:in `require'
	from /home/how/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/engine/commands.rb:7:in `<top (required)>'
	from bin/rails:13:in `require'
	from bin/rails:13:in `<main>'
```
`rails console` returns this:
```bash
/home/how/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/command/actions.rb:8:in `set_application_directory!': uninitialized constant Rails::Command::Actions::APP_PATH (NameError)
	from /home/how/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:129:in `perform'
	from /home/how/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /home/how/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/how/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /home/how/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/command/base.rb:63:in `perform'
	from /home/how/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/command.rb:44:in `invoke'
	from /home/how/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
	from /home/how/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/engine/commands.rb:7:in `require'
	from /home/how/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/engine/commands.rb:7:in `<top (required)>'
	from bin/rails:13:in `require'
	from bin/rails:13:in `<main>'
```

I checked the contribution instructions and wiki. They don't tell anything about setting up development environment.

**Comment by etewiah** [comment]
Hi Steve,  thanks for your interest in PWB.  

PWB is a rails engine - you can read more about engines here:

http://guides.rubyonrails.org/engines.html

This means that the secrets.yml file you need is in the /spec/dummy/config directory.

You will also need to go to the /spec/dummy directory to run "rails c" and "rails s".

**Comment by etewiah** [comment]
Hi Steve, I trust I have answered your questions fully so I'll close this issue.
